// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "aquaculture/models"

	mock "github.com/stretchr/testify/mock"
)

// PromoCodeRepository is an autogenerated mock type for the PromoCodeRepository type
type PromoCodeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: pcReq
func (_m *PromoCodeRepository) Create(pcReq models.PromoCodeRequest) (models.PromoCode, error) {
	ret := _m.Called(pcReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.PromoCode
	var r1 error
	if rf, ok := ret.Get(0).(func(models.PromoCodeRequest) (models.PromoCode, error)); ok {
		return rf(pcReq)
	}
	if rf, ok := ret.Get(0).(func(models.PromoCodeRequest) models.PromoCode); ok {
		r0 = rf(pcReq)
	} else {
		r0 = ret.Get(0).(models.PromoCode)
	}

	if rf, ok := ret.Get(1).(func(models.PromoCodeRequest) error); ok {
		r1 = rf(pcReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *PromoCodeRepository) GetAll() ([]models.PromoCode, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.PromoCode
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.PromoCode, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.PromoCode); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PromoCode)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *PromoCodeRepository) GetByID(id string) (models.PromoCode, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.PromoCode
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.PromoCode, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.PromoCode); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.PromoCode)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: pcReq, id
func (_m *PromoCodeRepository) Update(pcReq models.PromoCodeRequest, id string) (models.PromoCode, error) {
	ret := _m.Called(pcReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.PromoCode
	var r1 error
	if rf, ok := ret.Get(0).(func(models.PromoCodeRequest, string) (models.PromoCode, error)); ok {
		return rf(pcReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.PromoCodeRequest, string) models.PromoCode); ok {
		r0 = rf(pcReq, id)
	} else {
		r0 = ret.Get(0).(models.PromoCode)
	}

	if rf, ok := ret.Get(1).(func(models.PromoCodeRequest, string) error); ok {
		r1 = rf(pcReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPromoCodeRepository creates a new instance of PromoCodeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromoCodeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromoCodeRepository {
	mock := &PromoCodeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
